### ISSUE TITLE
Template Uses Bootstrap 3

### ISSUE THREAD

**Issue by Dave-LeDev** [projectknife/pkg-projectknife#12]
I could use a suggestion. My template is using Bootstrap 3 and thus uses different conventions of scaffolding than Bootstrap 2 does, which is what the classes of the component are dependent on. I can either patch the component with the right classes or inject just the scaffolding from BS2.x. What's the best approach to this?

...other than the option to select between the usage of BS2/3/4 in backend, if that's a feature you're willing to implement...

**Comment by eaxs** [comment]
We probably will not support any other framework that isn't officially used by Joomla itself. So for now that's BS2, and later BS4. But at least for BS3, there may be a clever way of doing it:
http://www.joostrap.com/support/tutorials-videos/206-boostrap2-to-bootstrap3-super-easy-update

I have not tested this myself yet, but it may actually work. If you know how to write PHP code and dont want to use ReReplacer, you could easily hook into the "onBeforeRender" system event, and replace the BS2 selectors with their BS3 equivalent.

**Comment by eaxs** [comment]
onBeforeRender doc: https://docs.joomla.org/Plugin/Events/System#onBeforeRender
Not much to go on, but it's pretty self-explanatory I'd say :)

**Comment by Dave-LeDev** [comment]
I'll have a look at those when I get a chance. Right now I have it patched by sideloading just the scaffolding. :P
