### ISSUE TITLE
Request: Display of All Milestones

### ISSUE THREAD

**Issue by sarrene** [projectknife/pkg-projectknife#13]
One of the things I loved about PF4 was how milestones could be sorted by Project. It would have the header of the project and show all milestones under that. Currently you can display all, but they are not under a Project Header, just lists it in the milestone information.

This really helps with visual viewing, and one thing that all of my developers from two different projects are asking for back.

Example of Milestones Default page when you are viewing all:
Project 1
    └ Milestone 1
    └ Milestone 2
Project 2
    └ Milestone 1
    └ Milestone 2

If this could be done for tasks as well, showing milestones, that would be brilliant. Being that you can have the header show for "Sort by Date", It would be nice to have the header for Projects and Milestones as well. 
Milestone 1
    └ Task 1
    └ Task  2
Milestone 2
    └ Task  1
    └ Task  2

Thank you

**Comment by eaxs** [comment]
This feature is still there. In fact we've expanded it to be dynamic, based on the 1st sorting field. Go to the milestones or task list, then click the list icon with the "20" next to it and change the 1st sorting field to "Project". It'll change the group headings from due dates to project titles. This also works for a lot of other fields, but not all :)

**Comment by sarrene** [comment]
Sorting is there and it does work. However, it does not show the header (and still is not in the correct order). 
https://gyazo.com/08bc8058278615ddf02520e806ac633b

Perhaps I am not explaining it well enough. let me know if i can explain or show some mockups instead. Sadly I do not have PF installed any longer.

Thank you
