### ISSUE TITLE
Request: Comment ability on Tasks

### ISSUE THREAD

**Issue by sarrene** [projectknife/pkg-projectknife#14]
A simple threaded comment system would be nice to have back for PK. It is something we miss. Any idea if this will be added back in? Does not need to be complex, can be fairly simple, but still able to allow updates, comments, questions, etc per task. 

Thank you

**Comment by eaxs** [comment]
I was really unhappy with the way the comments worked in PF4. If we bring them back, we'll redo the whole thing. In the meantime, any Joomla comment system should actually work, because they all use the Joomla events to render the form and the comments, and Projectknife provides the same plugin interfaces for all its contents.

**Comment by sarrene** [comment]
PF4 was not too bad. Though I did customize it a lot. And removed some of the aspects that were bloated for our project. 

I will have a look at a few, jcomments is the most common and i have used it in the past. 
Honestly, something simple is really all that is needed, with permissions of course. :)

Thank you :)

**Comment by sarrene** [comment]
Well, I took a look at jcomments, and it does not work out of the box. If i have to add the functionality in, that is going to take me a bit of time. And to be honest I do not have time for that right now. I am currently managing four groups and projects right now, two of them scheduled for release soon.

Do you have any other suggestions?

Thank you

**Comment by Dave-LeDev** [comment]
I'll see if Komento works.

**Comment by sarrene** [comment]
Dave, had you any luck? 
Still would be nice to have native support for this, as for teams that require agile development, comments and being able to update and keep everyone else updated is important.

**Comment by eaxs** [comment]
We've just added support for JComments. You have to install an extra plugin for it here: https://projectknife.net/jcomments-integration

If you need support for other comment extensions, please send a copy of the extension to support@projectknife.net and we'll see what we can do. If comment extensions dont work out of the box, they usually just require a simple plugin.

**Comment by sarrene** [comment]
Comments work nicely now, thank you very much. 

**One request:** Can we have the ability added in (if plugin is enabled) to display number of comments on Tasks, Milestones and Projects? This would really help to be able to see if new comments were added or not without having to go into each task/etc.  
(remember it is about improving workflow in this case)

Thank you,
Sarrene'

**Comment by eaxs** [comment]
Yes, I have added this feature in the newly released beta 4. You'll also have to update the jcomments plugin.
