### ISSUE TITLE
Missing Language Keys

### ISSUE THREAD

**Issue by Dave-LeDev** [projectknife/pkg-projectknife#16]
COM_MODULES_PKGANTT_OVERVIEW_FIELDSET_DESC
COM_MODULES_PKGANTT_DETAIL_FIELDSET_DESC

**Comment by eaxs** [comment]
Fixed, and a new version has been released with the other bug fixes as well:
https://projectknife.net/gantt-chart-site-module

Thanks!

**Comment by Dave-LeDev** [comment]
Nice!
