### ISSUE TITLE
Gantt Module: Tooltip Z-Index

### ISSUE THREAD

**Issue by Dave-LeDev** [projectknife/pkg-projectknife#17]
https://i.gyazo.com/a11f184864cf17d77e7b476b92c28511.png

Tinkering with z-index on related DIVs doesn't seem to work. Not sure what's forcing the tooltip behind. This behavior shows on the demo as well.

https://i.gyazo.com/beb1a630f688634022413249181f2d6c.png

**Comment by eaxs** [comment]
I was initially thinking it was a z-index issue, but it turned out to be the overflow on the left col:
`.fn-gantt .leftPanel` remove `overflow:hidden`. I'll get a new version up soon. Thanks!
