### ISSUE TITLE
Gantt Module: Mobile Display Not Responsive

### ISSUE THREAD

**Issue by Dave-LeDev** [projectknife/pkg-projectknife#18]
https://i.gyazo.com/52f4dc054170d4f30252d944dbf984b3.png

**Comment by eaxs** [comment]
I'm not sure I can change this behavior. From what I understand, the sizes are fixed, and determined when the page has loaded. So it is somewhat semi-responsive at least. If you reload the window at a small size, the chart will be rendered accordingly.

The whole thing is constructed around fixed and not relative sizes, sorry :(

**Comment by Dave-LeDev** [comment]
Hm. Honestly the presentation of information itself doesn't lend to mobile friendliness. I may just hide it all together for mobile.
