### ISSUE TITLE
Default Assignee

### ISSUE THREAD

**Issue by N6REJ** [projectknife/pkg-projectknife#2]
Is there someway we can please have auto assign a default assignee?  By default logged in user.

**Comment by eaxs** [comment]
It's not possible, but it's fairly easy to implement. I'll put it into the next beta release. Thanks!

**Comment by sarrene** [comment]
Please allow this to be an option in settings. We have one team that is fairly small and they pick up (assign themselves) the tasks as they progress through. This is common for some smaller development teams. 

Thank you
sarr

**Comment by N6REJ** [comment]
of course it would be an option :D
