### ISSUE TITLE
Blank Plugin Pages

### ISSUE THREAD

**Issue by empmdk** [projectknife/pkg-projectknife#21]
I have tried installing this several times, multiple versions of projectknife and joomla. Every time, the pkg is installed and menu is created. However, the menu has no sub-items and clicking "Projectknife" will lead me to a blank page in the Joomla admin.
I've gone through to make sure the included plugins are enabled and everything is. I'm currently stuck using the old ProjectFork and would like to transition into something that is being actively developed. If it helps, the ProjectKnife download is only 346KB while the older ProjectFork download is 1.31MB. Knife seems to me that it could be an incomplete package.

**Comment by eaxs** [comment]
Projectknife is definitely a lot smaller at its core - meaning the initial package that you get.

The Projectknife entry in the "Components" menu in the Joomla backend has no sub-menu this time around. It was really hard to maintain and would often be lost upon updating in Projectfork. So simply no longer do it.

If the dashboard looks empty like this, then that's normal (for now anyway):
![dashboard](https://cloud.githubusercontent.com/assets/489521/26405800/b5aa5242-4096-11e7-8ac0-d558b01d8c97.jpg)

You can publish any modules on the dashboard that you like, as explained here:
https://projectknife.net/support/15-documentation/projectknife-guide/14-dashboard-modules

You can get to the projects, milestones and tasks by using the left menu that should be visible on your dashboard.

Projectknife is currently in beta and we keep in that phase until we have roughly the features Projectfork had. Until then we also have a 25% discount for those wanting to upgrade step by step as we progress with new extensions and patches.

**Comment by empmdk** [comment]
I see. Thanks for making this clear.
