### ISSUE TITLE
Projectknife - Tasks

### ISSUE THREAD

**Issue by Christophe69** [projectknife/pkg-projectknife#24]
Hi,

I have some problems with the Task List module. (https://wayofgamers.fr/fr/dashboard).

Despite the fact that these tasks are not in public access, they are displayed .. while others who have the same type of access are not. This is an import from Projectfork 4 to Projectknife.

Even if I do not publish the task it remains in the list.
I also do not find the functionality, by task to be able to define access.

Best Regards

Christophe

**Comment by eaxs** [comment]
Just to provide some feedback on the issue so far: It'll be fixed in the next beta release. The module is pulling data from the main component - which is where the actual bug is. The next release is planned to come out next week!
