### ISSUE TITLE
Task editing in frontend

### ISSUE THREAD

**Issue by Sechslinden** [projectknife/pkg-projectknife#27]
Hi,

I want my users to edit tasks, but it's not possible. I set all permissions I found, on enabled, but it doesn't work. Only the super user can edit tasks.

What's curious: When I put a milestone- or task-**form** in the menue, it's no problem for the user to create a new milestone or task.
But when I put a milestone- oder task-**list** in the menu, and then they try to click on the "new" button, in the list, it says "record landing not allowed".
If they want to edit a Task it says "editing not allowed".

**Comment by eaxs** [comment]
Thanks, it should be fixed now. You can download the latest code here: 
https://github.com/projectknife/pkg-projectknife/archive/dev.zip

Simply the package through the Joomla installer and you should be good.
