### ISSUE TITLE
Copying / Template?

### ISSUE THREAD

**Issue by destrecht** [projectknife/pkg-projectknife#28]
I saw that there was a way to copy categories and tasks in PF. Is there a way to do that now, in PK? I have several projects that have the same tasks and milestones. Is there a way to set up a template or clone them and mass assign them to project/ category? 
I saw you mentioned Joomla tags, I have NO idea what that it or how they would be used in this instance.

**Comment by eaxs** [comment]
You can absolutely copy entire projects in Projectknife. In the frontend, click the "Edit" button at the top of the project list. Then select the projects you want to copy, and then click the "Copy" button back at the top.
You'll even get to choose whether to include milestones and tasks or not.

The Joomla tags allow you to categorize or label your data. It has no other purpose really.

**Comment by destrecht** [comment]
Gotcha- Ok, I guess it was easier than I realized.
