### ISSUE TITLE
Dashboard empty

### ISSUE THREAD

**Issue by N6REJ** [projectknife/pkg-projectknife#3]
Not sure what I'm doing wrong but dashboard is totally empty.
[http://www.texaslifestylesfurniture.com/index.php/dashboard](http://www.texaslifestylesfurniture.com/index.php/dashboard)

**Comment by palmok** [comment]
Hi,
Have you added modules (project, gantt, tasks, taskcount...) with the position pk-dashboard-bottom ?

Palmok

**Comment by N6REJ** [comment]
no, didn't know too, I couldn't find any docs either.

**Comment by palmok** [comment]
In fact, I think that the modules were installed during the installation of the app.
Perhaps that you have to publish them and/ore change the position which could not be good for your template ?

**Comment by N6REJ** [comment]
nah, and honestly, even if they were, they would still be available as 'new"
![image](https://cloud.githubusercontent.com/assets/1850089/24841027/f1e3ea40-1d3f-11e7-8f4c-e016e3ebc8d5.png)

**Comment by eaxs** [comment]
The modules which are currently available all require full access at the moment. We'll add some free modules in the future, but for now that's all we have, sorry. 
The dashboard is empty by default, as explained here: https://projectknife.net/support/15-documentation/projectknife-guide/14-dashboard-modules
