### ISSUE TITLE
New Project form: start and end dates

### ISSUE THREAD

**Issue by angek** [projectknife/pkg-projectknife#30]
when a newly created Project is saved (apply) without entering start and end dates the form's start and end dates remain blank.
steps to reproduce:
1. create new project without specifying start and end dates
2. click "save"
3. start and end dates remain blank (ie are not re-populated with their calculated values).

**Comment by eaxs** [comment]
This behavior is intended and hopefully explained a bit in detail here:
https://projectknife.net/support/15-documentation/projectknife-guide/12-dynamic-dates

In a nutshell: Empty dates are managed automatically until given a specific value by the user.

**Comment by angek** [comment]
The way dates are managed internally is irrelevant.
If I choose to not enter a start and end date for a new project and PK automatically determines these dates for me, as a user, I would still expect the automatically determined dates be returned and displayed after I've applied my changes.
