### ISSUE TITLE
New Task - progress and predecessor

### ISSUE THREAD

**Issue by angek** [projectknife/pkg-projectknife#32]
When creating a new task you are able to set the progress for this task even though you assign an uncompleted predecessor.

In the example below "Task Two" is a task that's still in progress.

![in_progress_task_as_predecessor](https://user-images.githubusercontent.com/1072484/27458251-70044038-57eb-11e7-98e1-a948644a9bb7.png)

I create a new task, set it's progress to 90% and then select "task two" as a predecessor.

![new_task_dep](https://user-images.githubusercontent.com/1072484/27458300-b0ed3c76-57eb-11e7-8934-d8294beff979.png)

There seems to be no control logic in the predecessor select2 to prevent this.

![task_list_dep](https://user-images.githubusercontent.com/1072484/27458305-b6fb224a-57eb-11e7-8c30-c7e9a3464bd4.png)

**Comment by micker** [comment]
hello i am interessting by this how to test it ?

**Comment by eaxs** [comment]
This should be fixed now. Thanks!
