### ISSUE TITLE
Dashboard of project

### ISSUE THREAD

**Issue by yasarts** [projectknife/pkg-projectknife#36]
The dashboard doesn't display the list of milestones and/or task of a project ; not even a link to them.
That's not easy to use.
It doesn't display the % of avancement of the project too.

PK 5.0.0 Beta5
J!3.7.2

**Comment by eaxs** [comment]
The dashboard modules are now additional addons which you can get through Full Access:
https://projectknife.net/full-access

But you can display any module you like on the dashboard, as explained here:
https://projectknife.net/support/15-documentation/projectknife-guide/14-dashboard-modules
