### ISSUE TITLE
Gantt module and cache

### ISSUE THREAD

**Issue by yasarts** [projectknife/pkg-projectknife#37]
If I embed the gantt module in a presentation of categorie, and if I click on a milestone, when I come back to the page, the gantt diagramm isn't display.
If I erase the cache, it works again.
(that the same thing in a dashboard for a spectific project).

**Comment by eaxs** [comment]
Are you loading the module though the content plugin into the category description?

**Comment by eaxs** [comment]
I've had a another look and the issue is with how caching works. The problem is that the module is entirely rendered through javascript. And the javascript is loaded through the module, which is never loaded when it is cached :( 

There is unfortunately nothing that can be done about this, sorry!
