### ISSUE TITLE
Styling broken in Bootstrap 3

### ISSUE THREAD

**Issue by N6REJ** [projectknife/pkg-projectknife#4]
Not sure why but the styling totally falls apart in BS3
http://www.texaslifestylesfurniture.com/index.php/dashboard

**Comment by eaxs** [comment]
Yes, your template uses a different CSS framework it seems. Projectknife uses bootstrap 2, which comes with Joomla by default, and that's how all default extensions are designed.

I'm afraid there is nothing I can do short term. Long term, we have to find a reasonable way to support other CSS frameworks though. For now, you can either switch to bootstrap 2 template, or you'll have to manually override each Projectknife layout to work with your template's framework.

**Comment by N6REJ** [comment]
you wouldn't think it would be that big a issue, as bs2 and bs3 are extremely similar and to be honest my template takes care of the biggest changes itself.  And of course bs4 is right around the corner both for J! and for the world @ large.

**Comment by eaxs** [comment]
I'm no CSS expert, but BS3 is not backwards-compatible with BS2, according to the official statement:
http://getbootstrap.com/migration/

Someone must have been smart to migrate the selectors that have been dropped in BS3, but I can't seem find anything.

Several sources mention that Joomla 4 will go straight to Bootstrap 4, AND will make it easier to support other frameworks as well. I'm definitely looking forward to that :) I'm not defending BS2 in any way btw, but it is the current Joomla default, and that's what were rolling with.

**Comment by N6REJ** [comment]
totally understand and agree.. there are a couple of "converters" if you will albeit non are perfect.  In our case we have a custom.js that handles it and until now never had a issue.  
here's one attempt but not what I was thinking of..
https://github.com/divshot/bootstrap3_upgrader  
https://github.com/Claromentis/bootstrap2-3converter may or may not help... 

and Yeah, J! 4 is using BS4 so that will make life nice LOL..
I'm excited to see the change, going to make my life SOOO much easier... course requires me to totally change my template but thats ok.
