### ISSUE TITLE
Cannot select date(s) when creating projects or tasks on front end...

### ISSUE THREAD

**Issue by jvigil48** [projectknife/pkg-projectknife#41]
When creating a project or task on the front end, I am unable to modify the start and due dates.  I can perform this function on the back end but that is not preferred.  Is there a privilege or setting that needs to be changed to allow for date setting on the front end?

**Comment by angek** [comment]
What version of Projectknife are you using? I've just tried it with 5.0.0.beta.5 and when I created a new project from the front end I was able to set the start and end dates successfully

**Comment by jvigil48** [comment]
I am using the latest version 5.0.0 beta 6.  In fact I just purchased and downloaded last Thursday.

**Comment by angek** [comment]
@jvigil48 I dont have access to the pro version but I suspect that the core PK is the same.
Let me update mine to 5.0.0 beta 6 and see what happens.

**Comment by jvigil48** [comment]
Sounds good let me know the results.  I installed on two separate sandbox copies of my site and the same problems exist. Not only this problem with the dates but also I cannot get the user activity module or table to show data if logged in as any user less than Super User.

**Comment by angek** [comment]
Im not a member of the PK team but if you feel comfortable enough sharing a login (creating an account) to one of your sandbox sites I'd be more than happy to take a look at yours.

**Comment by jvigil48** [comment]
I can do that...am going in to create an account right now.  Get right back to you

**Comment by angek** [comment]
email me at angek[at]angekdesign[dot]com[dot]au

**Comment by jvigil48** [comment]
will do

**Comment by angek** [comment]
got it. Thanks!

**Comment by jvigil48** [comment]
just sent you a new email with the back end access.  Thank you.

________________________________

**Comment by angek** [comment]
you've got a javascript conflict that's causing the problem. Is there anything you dont want me to touch on that sandbox?

**Comment by angek** [comment]
![calendar_error](https://user-images.githubusercontent.com/1072484/29392688-c5e74482-8342-11e7-9dd8-92726de793f9.png)

**Comment by jvigil48** [comment]
please feel free to do what you need to.  It is just a sandbox that I can always re-establish. if it breaks somthing else I will discover it.   FYI...PK on the front end is accessible under the "Site Tools" menu under "Program Management" submenu.  Thanks

**Comment by angek** [comment]
cool... 
So setting dates for projects works from the backend but no the frontend. There are 2 calendar scripts being loaded. IT may be the cause of your issue.... just trying to figure out where the extra one is being loaded from.

**Comment by jvigil48** [comment]
So this site at one time had Projectfork intalled but I have since removed the PF modules and plugins and replaced with PK.  However, I loaded the two together to test the migration tool.  Not sure if that is any part of the problem.

**Comment by angek** [comment]
I can confirm that it is a calendar.js conflict. I've added the extra calendar.js file through my template and it causes the same issues for me. Now to find where it's being loaded from in your system.

**Comment by jvigil48** [comment]
Thanks again.  I sincerely appreciate your support.

**Comment by angek** [comment]
can you try it now and let me know if it all works for you.

**Comment by jvigil48** [comment]
Hello, I tested this this morning and the date selection still does not work on the front end.

**Comment by jvigil48** [comment]
We did some custom coding where in we used JHTML Calendar control. We removed the developed custom code to see if it is conflicting but that is not the case. Here is a snippet of the calendar code what we used for one of the pages and the link for JHTML Calendar control.

https://docs.joomla.org/JHTML/calendar

![code](https://user-images.githubusercontent.com/24420211/29430837-2bd40bda-8353-11e7-8704-1b31d21fefe5.JPG)

**Comment by jvigil48** [comment]
So please note that this is my 3rd post to this thread today.  I did a search on my server for the calendar.js files and the attached image shows the directories for the files found (not sure if this helps).

![calendarfiles](https://user-images.githubusercontent.com/24420211/29437117-355cf068-836c-11e7-8016-5e0b9fa75bb8.png)

**Comment by angek** [comment]
Hey @jvigil48 I installed a plugin on your site. Thought I had it enabled and dont recall disabling it.
It basically allows me to remove certain scripts from the head of your pages. AS you can see from the image below I remove the offending scripts (none of which are PK related) 
![mootools](https://user-images.githubusercontent.com/1072484/29444641-acab7ffa-8424-11e7-8abf-b8708e129742.png)
and have been able to test successfully.
![test](https://user-images.githubusercontent.com/1072484/29444678-f7213dfe-8424-11e7-97eb-e7497beb44fb.png)
Im not sure which of your other components and/or plugins are adding the extra Calendar initialisation into your documents but suffice to say that given it now works on yours with the plugin I installed and it defs works on a standard Joomla installation using Joomla's default templates the problem is not with PK. I also noticed that the template you're using is pretty old (released back in 2012)

**Comment by jvigil48** [comment]
Hello Angek,  thank you for assisting me on this.  I do realize the template is older and I probably need to consider moving to a newer version.  Do I need to keep the Mootools plugin running or are you suggesting that I disable it?

**Comment by angek** [comment]
Unless you can find the component or plugin that's adding the extra calendar javascript I suggest you keep the plugin running.
