### ISSUE TITLE
Taskcounter

### ISSUE THREAD

**Issue by palmok** [projectknife/pkg-projectknife#5]
Hi,
I am using Projectknife from 2 days, except 3 difficulties 

1- The task counter is not working well, except if I am Logged in as superuser ;
2- From the list of tasks on the Dashboard, it's ok when I select a task, well displayed, bur the menu on the left (Apptheme) or any "back, return ..." is not displayed;
3- How to do, what have I to do to display the numbers of tasks as on the demo site (centered, colored background...) ?

Sorry for my bad english !

Regards

Palmok

**Comment by eaxs** [comment]
Regarding question 1, can you explain how it does not "work well"? Please describe what is different, or what result you are expecting.

Regarding question 2: I have to get back to you on that. I'll just mention that we haven't tested any of the Projectfork templates with Projectknife. So it is quite possible that they won't work well together.

Regarding question 3: Edit the module, and the add the css selectors that you want in the field "Link Class". You can use any selectors you like, but for the demo we use bootstrap. If you have that (I think a lot of templates do), you can look at the button classes here, and copy them directly: http://getbootstrap.com/2.3.2/base-css.html#buttons

Feel free to experiment though :)

**Comment by eaxs** [comment]
I've fixed the counter issue! We've also released counter modules for projects and milestones: https://projectknife.net/downloads

If you still have issues with them, please open another issue. Thank you!
