### ISSUE TITLE
ProjectKnife JS/Bootstrap conflict

### ISSUE THREAD

**Issue by sarrene** [projectknife/pkg-projectknife#6]
There is a conflict with some template frameworks and the task Progress Type. The "Simple to-do" works fine, however if you go to the slider and percentage base, it breaks a lot of other aspects of the template. The list on the Vertex Framework, T3 framework Gantry 4 (to some minor degrees):
- Menu
- CSS Styling
- Drop down menus
- Input boxes
- Pop up panels

The PK task progress sliders also disappear and are not present even in the html output. Instead it is replaced with a text field box. 

Vertex framework seems to have the most issues. You can download the Vertex framework and sample template to view the problems. I do not have this visible to the public on any site, however I can grant access if you wish to see it in action with ProjectKnife set up. 

I do want to note that any default template works quite well, or one not built upon a bootstrap framework. This is very odd the results. 

Thank you,
Sarr

**Comment by eaxs** [comment]
Please see my answer I gave just a moment ago elsewhere: https://github.com/projectknife/pkg-projectknife/issues/6

Basically, we're running with the things that Joomla provides out of the box. So that's bootstrap 2. Right now I honestly don't have a solution for you. The thing is that we can't support every major framework out there, because it would be impossible to maintain, not the mention the mess it would make in our markup. 

Maybe that's just the price people have to pay if there don't use bootstrap2 templates. Not saying that it's your fault though. But it's logical that if you (or the template dev) want to use a different framework , you have to accept that not everything will work as well as it would otherwise.

So the best option would be to switch to a boostrap 2 template (at least for Projectknife menu items), or to add layout overrides that work with your prefered css framework.

**Comment by sarrene** [comment]
I have not delved much into other template frameworks minus Vertex, though I had tested a few out to see if this was template specific or not. 

Vertex framework and S5 templates do pull from the default bootstrap that is built into Joomla, so it is using the J3.2 version. 

I hope you reconsider, I have been a supporter of PF and now PK for many years across multiple licenses. PF and PK now, are very valuable and useful tools that I have very easily convinced other companies to use as well. As COO, we are currently looking at a much larger scale with other game developers and their sites across two game engines/companies- if we can get things working out well out of the box.

Thank you,
Sarr

**Comment by eaxs** [comment]
We are discussing the issue and are trying to come up with a solution. Nothing concrete so far, but we are aware of the fact that people need better support for other css frameworks.

**Comment by sarrene** [comment]
Thank you very much, 
We just had several new clients sign up and this is something I would love to be able to direct them to, once it is working fairly well. Standard css adjustments is not a problem. It is the weird js conflict that occurs on most frameworks, some more than others. 

If you like to send me a pm or email, I am more than willing to give you access to view the effect on a live site. The email attached is my y! email so should be easy to find me in your accounts. I might possibly be able to assist/help out in some ways with the basic styling issues across other templates if time allows. 

Thank you again,
Sarrene'

**Comment by sarrene** [comment]
Any update to the conflicts causing the Progress % to be killed out?
![weird01](https://cloud.githubusercontent.com/assets/8040712/25287372/1d3d9d00-268f-11e7-9bbe-49fd12c7398c.png)

( https://gyazo.com/508cb747fd9dcda60464cf7be836eab4 )

Thank you

**Comment by Dave-LeDev** [comment]
Your hotfix for Bootstrap and ReReplacer is so far working for me.

https://github.com/projectknife/pkg-projectknife/issues/12

**Comment by sarrene** [comment]
Vertex framework is still using bootstrap 2 and pull directly from Joomla's default. So using the ReReplacer will not be an option for me and the other games/teams sites either. 

Until this is fixed, I cannot in good faith refer ProjectKnife to other game/web devs at this time. We are currently sitting at over 800 active developers, and just over 30 with their own sites right now. It would be nice to be able to refer them to PK instead of them using external PM software. 

With this closed, I hope that Tobias still can read/view to understand the importance for all sides to get this working. My above post shows how the percentages is removed from the html output. 

Thank you,
Sarrene'
