### ISSUE TITLE
Styling issue(s)

### ISSUE THREAD

**Issue by haasdijk** [projectknife/pkg-projectknife#7]
First of all, my compliments for this great extension. I know nothing about your last project, ProjectFork, but this one is very good.

After installation there are a few things that are not OK for me. Our platform is on the latest Joomla version, latest Gantry btw.

When the Gantt is displayed, "time" is on another line then the tasks.
 
![testpagina](https://cloud.githubusercontent.com/assets/10158720/24910006/9a480e0a-1ec6-11e7-96ff-b31976647f96.png)

The consequence is that the tasks and the timeline diverge in the Gantt. It does not matter how wide I make the first column. Is this a styling issue?
Alignment is anyway not always pretty. However, you have some updates in preparation so I understand. I hope that this will also get at least some attention.

We also experiensing the Framework issue i think. We use the Gantry 5 Framework with matching templates. Offcourse i can use the Protostar template when displaying ProjectKnife data but that is not pretty. It is what it is but when you guys can give this a look that would be nice.

Again, a great extension. I will definitely use it. But i'll wait for the next few updates before going live.

Regards,
Peter

**Comment by eaxs** [comment]
Thank you for your support, we really appreciate it!
This definitely is a styling issue that is related to non-bootstrap templates. Seems like this has become a hot topic now and everyone is complaining about it :( 
The problem with the gantt chart in particular is that it is entirely javascript driven and relies on specific (bootstrap) selectors. So that's really tricky to deal with.

We are discussing ways to deal with the different css frameworks internally, but no solution or decision yet. Sorry.

**Comment by haasdijk** [comment]
No problem. In the meantime I'll use the protostar template instead. There is another strange issue i'd like to mention here. I can't get the Gantt displayed in the frontend. Even when i use exactly the same settings i use in the backend. Any ideas where to look for?

**Comment by eaxs** [comment]
You mean the chart is not displayed at all? That's most likely a javascript related issue then. Because as I've said, the module rendered through JS. Can you email a link to your site to support@projectknife.net so I can take a look?

**Comment by sarrene** [comment]
If you have a custom css file in your template or you are willing to add some custom to the bottom of your primary template.css (or what ever it might be called for your framework), you can easily add the following in and it should help.

The issue with this one I saw on Gantry, and a few others was that the template was overriding the PK css in some areas. Here is what you can add and see if it helps **as a quick fix**:
```
.fn-gantt .spacer {background-color:#f6f6f6!important}
.fn-gantt .leftPanel .name, .fn-gantt .leftPanel .desc {background-color:#f6f6f6!important}
```
That will help since the fn-gantt bar does show visible overflow. The left panels are layers (divs) that sit on top of those that normally hides them. 

Let me know if that works or not.

**Comment by haasdijk** [comment]
Tobias,

You pointed me in the right direction. Wat i did:
- unabled the JavaScript Frameworks/Bootstrap option;
- enabled Bootstrap - Popovers in JF Elements.
Now the Gantt is shown in the frontend. Nice.

What i haven’t figured out yet is why in the backend the months are not on the same row (the rest seems to be OK) and in the frontend why the duration is on a different row then the task. I saw you closed the issue on Github. Do you want me to reply there instead of in the mail. For future reference and questions from other users that is?

Regards,
Peter

                                                          
Peter Haasdijk

Vroonland 30, 4112 NW  BEUSICHEM
t +31 (0)345 78 56 89 | m +31 (0)6 13272159 | e peter@haasdijk.com
www.haasdijk.com
www.linkedin.com/in/haasdijk
twitter.com/haasdijk

**Comment by haasdijk** [comment]
@sarrene, i've tried the quick fix you suggested. It didn't work for me. Thanks anyway!
Regards,
Peter

**Comment by eaxs** [comment]
I am re-opening the issue.
We've released a new version for the admin gantt chart, which should solve the display issue. 
I had no visual glitches with the frontend module in combination with your template. I will take a look again on your site, if the login is still active :)

**Comment by haasdijk** [comment]
Tobias,

Your account is still active. If you have any trouble logging in, please let me know.

Regards,
Peter

**Comment by eaxs** [comment]
I figured out part of the issue. You'll have to edit your template through the gantry component, and add the following code to the "Custom Code" field, in the "Head Properties" section:
`<style type="text/css">.fn-gantt{box-sizing:content-box;}</style>`

This will correct the layout, but it does not account for the labels turning invisible upon hovering. This part is not a new issue in fact. We've had this in Projectfork 4 too, and I think it was related to a javascript conflict or something within bootstrap. I'll have to dig out the solution to that.

**Comment by eaxs** [comment]
Do you remember my email where I asked you to add: `JHtml::_('behavior.tooltip');` to the index.php of your template? If you still have that code in there, please remove it. That might actually solve it.

If not, I'm sure it has something to do with the tooltips, but I can't remember what it was exactly right now :)

**Comment by haasdijk** [comment]
OK, that's nice. In the frontend it looks quite OK now. I have a few day's off so i'll check the backend later.
Thanx!
Peter

![frontend](https://cloud.githubusercontent.com/assets/10158720/25314271/52aabfd2-2841-11e7-8011-c1e0e4e8b24e.png)
