### ISSUE TITLE
Default end/due date

### ISSUE THREAD

**Issue by sarrene** [projectknife/pkg-projectknife#8]
I noticed on this version, if no due date is set it will default to the current day/time that the project/milestone/task was created. Could we have it so no date is created by default? 

This would make it much easier for Task Managers/Teams/Companies whom are still in their planning stages, or those ongoing projects/milestone/tasks that might not have an ending due date.

Request: Perhaps instead of defaulting to the current date and time, it would default to no due date/blank, perhaps just a tack "-" (or nothing at all) would display.

Thank you,
Sarrene'

**Comment by eaxs** [comment]
You can leave the dates empty for projects and milestones. If you do so, Projectknife will manage it for you, as described here: https://projectknife.net/support/15-documentation/projectknife-guide/12-dynamic-dates

There is a lot of code that relies on the fact that tasks require concrete start and due dates, so it won't be possible to change that easily, as it would mess pretty a lot of things. A workaround could be, if you'd tag tasks as "tentative", so everyone knows it's not concrete just yet.

I agree that we need more tools to manage dates in the future though.
