### ISSUE TITLE
Project Still Supported?

### ISSUE THREAD

**Issue by Dave-LeDev** [projectknife/pkg-projectknife#9]
[Recent JED reviews](https://extensions.joomla.org/extension/projectknife/) have flagged this project as unsupported and I'd like to see if the project is still maintained before taking on a subscription.

**Comment by eaxs** [comment]
The project is active, and we provide regular updates for Projectknife and all extensions. Not sure why the last reviewer said suggested that the project was dead. I'm guessing because the used Projectfork 4 and could not move instantly to Projectnife 5 (the current version in development).
